### ISSUE TITLE
 Can't resolve 'https' in Angular 11

### ISSUE THREAD

**Issue by VenturaPino** [ctmil/ng-odoo-connect#1]
For angular **v11.0.0** the rute you explain on the Readme doenst exist.

Instead it exists : 
![image](https://user-images.githubusercontent.com/25476739/117147962-0dac9780-adb6-11eb-93fe-5e399008fbc8.png)

Ng serve shows this error:
`Error: ./node_modules/xmlrpc/lib/server.js
Module not found: Error: Can't resolve 'https' in 'C:\Users\ventu\Desktop\TRABAJO\bitmark-front\node_modules\xmlrpc\lib'`

**Comment by ibuioli** [comment]
Yes, they change that route, now you need search here:

```
node_modules/@angular-devkit/build-angular/src/webpack/configs/browser.js
```
